# Generated by Django 5.2.3 on 2025-06-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
