# Generated by Django 5.2.3 on 2025-06-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_tournament_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
