# Generated by Django 5.2.3 on 2025-06-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_match_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="field",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
