# Generated by Django 5.2.3 on 2025-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_match_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="stage",
            field=models.CharField(
                choices=[
                    ("GROUP", "Group Stage"),
                    ("SEMI_FINAL", "Semifinale"),
                    ("FINAL_1_2", "Finale"),
                    ("FINAL_3_4", "3º-4º posto"),
                    ("FINAL_5_6", "5º-6º posto"),
                    ("FINAL_7_8", "7º-8º posto"),
                ],
                max_length=20,
            ),
        ),
    ]
