# Generated by Django 5.2.3 on 2025-06-24 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_match_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="team1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team1",
                to="main.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team2",
                to="main.team",
            ),
        ),
    ]
