# Generated by Django 5.2.3 on 2025-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_match_team1_alter_match_team2"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="set1_team1",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="set1_team2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="set2_team1",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="set2_team2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
