# Generated by Django 5.2.3 on 2025-07-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_match_set1_team1_match_set1_team2_match_set2_team1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="stage",
            field=models.CharField(
                choices=[
                    ("GROUP", "Group Stage"),
                    ("SEMI_FINAL", "Semi"),
                    ("FINAL_1_2", "Finale"),
                    ("FINAL_3_4", "3º-4º"),
                    ("FINAL_5_6", "5º-6º"),
                    ("FINAL_7_8", "7º-8º"),
                ],
                max_length=20,
            ),
        ),
    ]
